name: Deploy Django to EC2

on:
  push:
    branches:
      - main  # Adjust to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test  # Specify the "test" environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Match your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Print EC2 Host
        run: |
          echo "Deploying to EC2 host: ${{ secrets.EC2_HOST }}"

      - name: Deploy to EC2
        env:
          EC2_USER: ubuntu  # EC2 user (e.g., "ec2-user" for Amazon Linux, "ubuntu" for Ubuntu)
          EC2_HOST: ${{ secrets.EC2_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > ec2_key.pem
          chmod 600 ec2_key.pem

          # Disable host key checking and copy files to EC2 instance
          scp -o StrictHostKeyChecking=no -i ec2_key.pem -r ./* $EC2_USER@$EC2_HOST:/home/$EC2_USER/cicdproject

          # Disable host key checking for SSH and restart the Django service
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem $EC2_USER@$EC2_HOST << EOF
            cd /home/$EC2_USER/cicdproject
            source venv/bin/activate  # Activate virtual environment
            pip install -r requirements.txt  # Install any new dependencies
            python manage.py migrate  # Run migrations
            python manage.py collectstatic --noinput  # Collect static files

            # Restart Gunicorn or your WSGI server
            sudo systemctl restart gunicorn
            sudo systemctl reload nginx
          EOF
