name: Deploy Django to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to EC2
        env:
          EC2_USER: ubuntu
          EC2_HOST: ${{ secrets.EC2_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > ec2_key.pem
          chmod 600 ec2_key.pem

          ssh -o StrictHostKeyChecking=no -i ec2_key.pem $EC2_USER@$EC2_HOST << EOF
            # Update the package list and install necessary packages
            sudo apt update
            sudo apt install -y python3 python3-pip python3-venv nginx

            # Set up application directory
            mkdir -p /home/$EC2_USER/cicdproject
            cd /home/$EC2_USER/cicdproject

            # Create and activate a virtual environment
            python3 -m venv venv
            source venv/bin/activate

            # Install dependencies from requirements.txt
            pip install -r requirements.txt

            # Run Django management commands
            python manage.py migrate
            python manage.py collectstatic --noinput

            # Configure Gunicorn if not set up
            sudo tee /etc/systemd/system/gunicorn.service > /dev/null <<EOT
            [Unit]
            Description=gunicorn daemon
            After=network.target

            [Service]
            User=ubuntu
            Group=www-data
            WorkingDirectory=/home/ubuntu/cicdproject
            ExecStart=/home/ubuntu/app/venv/bin/gunicorn --workers 3 --bind unix:/home/ubuntu/app/gunicorn.sock cicdproject.wsgi:application

            [Install]
            WantedBy=multi-user.target
            EOT

            # Start and enable Gunicorn
            sudo systemctl daemon-reload
            sudo systemctl start gunicorn
            sudo systemctl enable gunicorn

            # Configure Nginx
            sudo tee /etc/nginx/sites-available/cicdproject > /dev/null <<EOT
            server {
                listen 80;
                server_name YOUR_SERVER_IP_OR_DOMAIN;

                location = /favicon.ico { access_log off; log_not_found off; }
                location /static/ {
                    root /home/ubuntu/app;
                }

                location / {
                    include proxy_params;
                    proxy_pass http://unix:/home/ubuntu/app/gunicorn.sock;
                }
            }
            EOT

            sudo ln -sf /etc/nginx/sites-available/cicdproject /etc/nginx/sites-enabled
            sudo nginx -t
            sudo systemctl restart nginx
          EOF
