name: Deploy Django to EC2

on:
  push:
    branches:
      - main  # Adjust to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Match your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python manage.py test

      - name: Deploy to EC2
        env:
          EC2_USER: ubuntu  # EC2 user (e.g., "ec2-user" for Amazon Linux, "ubuntu" for Ubuntu)
          EC2_HOST: ${{ secrets.EC2_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > ec2_key.pem
          chmod 600 ec2_key.pem

          # Copy files to EC2 instance
          scp -i ec2_key.pem -r ./* $EC2_USER@$EC2_HOST:/home/$EC2_USER/app

          # SSH into the EC2 instance and restart the Django service
          ssh -i ec2_key.pem $EC2_USER@$EC2_HOST << EOF
            cd /home/$EC2_USER/app
            source venv/bin/activate  # Activate virtual environment
            pip install -r requirements.txt  # Install any new dependencies
            python manage.py migrate  # Run migrations
            python manage.py collectstatic --noinput  # Collect static files

            # Restart Gunicorn or your WSGI server
            sudo systemctl restart gunicorn
            sudo systemctl reload nginx  # Restart Nginx if you’re using it
          EOF
